# Generated by Django 3.1.7 on 2021-03-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadcsv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadCSV',
            new_name='CSVs',
        ),
    ]
