# Generated by Django 3.1.7 on 2021-03-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210327_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSVs',
            new_name='Csv',
        ),
    ]
